#!/bin/sh
# build.sh - Arthic 64.
#
# Usage:  ./build.sh          build only
#         ./build.sh run      build, then boot it in QEMU
#         ./build.sh clean    delete build products
#
# On Arch:  sudo pacman -S base-devel qemu-system-x86 qemu-ui-gtk
#
# Note it is qemu-system-x86_64 now, not i386 - the kernel is 64-bit.

set -e

BUILD=build
INCLUDE=include

# Flags that differ from the 32-bit build, and why:
#   -m64                  obviously
#   -mno-red-zone         REQUIRED. The 64-bit ABI lets a function use 128
#                         bytes below the stack pointer without reserving it.
#                         An interrupt pushes onto that same area, silently
#                         corrupting whatever was there. Every 64-bit kernel
#                         turns this off; forgetting produces bugs that appear
#                         only when an interrupt lands in the wrong instruction.
#   -mgeneral-regs-only   no SSE registers, which are not saved on interrupt
#   -fno-pie -no-pie      no position-independent code
#   -fstack-protector-all a canary in every function with a local array,
#                         checked on return. Needs __stack_chk_guard and
#                         __stack_chk_fail to exist - see kernel/ssp.c. This
#                         flag was -fno-stack-protector in every earlier
#                         version of this file, because those two symbols did
#                         not exist yet - not because stack smashing did not
#                         matter.
#   -mstack-protector-guard=global
#                         REQUIRED alongside the flag above, and easy to miss.
#                         On x86_64, GCC's DEFAULT is to read the canary from
#                         %fs:0x28 - a thread-local-storage slot glibc sets up,
#                         which nothing in this kernel provides. Without this
#                         flag, every canary check compares that fixed,
#                         meaningless address against itself, always passes
#                         regardless of what actually happened to the stack,
#                         and __stack_chk_guard sits linked in and completely
#                         unread. This flag tells GCC to use a plain global
#                         symbol instead - exactly the one kernel/ssp.c
#                         defines - which is the convention every freestanding
#                         x86_64 kernel actually uses for this reason.
CFLAGS="-m64 -std=gnu11 -ffreestanding -nostdlib -fno-builtin \
        -fstack-protector-all -mstack-protector-guard=global \
        -mno-red-zone -mgeneral-regs-only \
        -fno-pie -I$INCLUDE -Wall -Wextra -O2"

if [ "$1" = "clean" ]; then
	rm -rf "$BUILD" arthic64.bin arthic64-boot.bin
	echo "cleaned"
	exit 0
fi

mkdir -p "$BUILD"

# ---- the user program -------------------------------------------------------
# Built completely separately from the kernel: its own linker script, its own
# load address, no shared headers, its own ELF64 file stored on the disk. The
# kernel carries no copy of it - unlike stage 3's embedded demo, this one is
# read off ArthicFS at run time.
echo "compiling  user/prog.c"
# Deliberately NOT $CFLAGS here - the stack protector needs __stack_chk_fail,
# which lives in kernel/ssp.c and is not linked into this standalone program.
# A user program wanting the same protection would need its own copy of that
# symbol, the same way it has its own copy of everything else it needs -
# nothing about ring 3 shares code with the kernel by default.
USER_CFLAGS="-m64 -std=gnu11 -ffreestanding -nostdlib -fno-builtin \
        -fno-stack-protector -mno-red-zone -mgeneral-regs-only \
        -fno-pie -I$INCLUDE -Wall -Wextra -O2"
gcc $USER_CFLAGS -c user/prog.c -o "$BUILD/prog.o"

echo "linking    user program (ELF64)"
ld -m elf_x86_64 -T user/prog.ld -o "$BUILD/prog.elf" "$BUILD/prog.o"
cp "$BUILD/prog.elf" user_prog.elf

# The whole ELF64 file becomes a C array the kernel can carry and write to
# disk via 'install'. od + awk only, so this does not depend on xxd being
# installed - same trick the 32-bit branch's build.sh uses.
{
	printf '/* Generated by build.sh from user/prog.c - do not edit. */\n'
	printf 'const unsigned char prog_elf_blob[] = {\n'
	od -An -v -tx1 "$BUILD/prog.elf" | awk '{for(i=1;i<=NF;i++) printf "0x%s,", $i; print ""}'
	printf '};\n\n'
	printf 'const unsigned int prog_elf_blob_length = sizeof(prog_elf_blob);\n'
} > "$BUILD/prog_blob.c"

echo "compiling  prog_blob.c"
gcc $CFLAGS -c "$BUILD/prog_blob.c" -o "$BUILD/prog_blob.o"


for src in boot/boot.s kernel/interrupts.s kernel/syscall_entry.s kernel/switch.s; do
	obj="$BUILD/$(basename "$src" .s).o"
	echo "assembling $src"
	gcc -m64 -c "$src" -o "$obj"
done

for src in kernel/main.c kernel/idt.c kernel/shell.c \
           mm/pmm.c mm/paging.c mm/kheap.c \
           kernel/gdt.c kernel/tss.c kernel/syscall.c kernel/usermode.c kernel/task.c kernel/lock.c kernel/pipe.c \
           drivers/ata.c fs/fs.c kernel/loader.c kernel/ssp.c \
           drivers/terminal.c drivers/keyboard.c drivers/timer.c \
           lib/string.c; do
	obj="$BUILD/$(basename "$src" .c).o"
	echo "compiling  $src"
	gcc $CFLAGS -c "$src" -o "$obj"
done

echo "linking    arthic64.bin"
KERNEL_OBJS=$(ls "$BUILD"/*.o | grep -v '/prog\.o$')

gcc -m64 -no-pie -Wl,--build-id=none -T linker.ld -o arthic64.bin \
    -ffreestanding -nostdlib -O2 $KERNEL_OBJS

# QEMU's -kernel only accepts a 32-bit multiboot image, and refuses a 64-bit
# ELF outright. The instructions inside are unaffected by the container format,
# so objcopy rewrites the ELF headers to elf32-i386 and leaves the code alone.
# This works only because the kernel is linked low - every address fits in 32
# bits. A kernel in the upper half of the address space would need a real
# bootloader and an ISO instead.
objcopy -O elf32-i386 arthic64.bin arthic64-boot.bin

echo
echo "built: arthic64.bin (and arthic64-boot.bin for QEMU)"

if [ "$1" = "run" ]; then
	# A disk image for the filesystem to live on, created once and kept
	# between runs so files persist - the same reasoning as the 32-bit
	# branch's arthic.img, just not the same file, since the two kernels
	# use incompatible on-disk layouts.
	DISK=arthic64.img
	if [ ! -f "$DISK" ]; then
		echo "creating $DISK (16 MB)"
		dd if=/dev/zero of="$DISK" bs=1M count=16 2>/dev/null
	fi

	echo "starting qemu ..."
	qemu-system-x86_64 -no-reboot -m 128M -kernel arthic64-boot.bin \
	    -drive file="$DISK",format=raw,if=ide
fi
