/* loader.c - turning a file into a running program.
 *
 * This is where everything so far comes together. Read bytes from ArthicFS,
 * ask the frame allocator for physical memory, use the MMU to make that memory
 * appear at the address the program was linked for, mark it user-accessible,
 * and drop to ring 3. Filesystem, allocator, paging, TSS, syscalls - all of it,
 * for one purpose.
 *
 * THE PROGRAM DESCRIBES ITSELF
 *
 * The file is ELF. Rather than the loader knowing where the program wants to
 * live and guessing at its structure, the program says so: an entry point, and
 * a table of segments each carrying an address, a size, and permissions.
 *
 * The loader's job becomes mechanical - walk the program headers, and for each
 * one that says PT_LOAD, put the requested bytes at the requested address with
 * the requested flags. No assumptions.
 *
 * WHAT THAT BUYS
 *
 * Code is mapped read-only and executable; writable data is mapped read-write.
 * The program cannot modify its own instructions, which with a flat image was
 * impossible to arrange because nothing distinguished the two.
 *
 * And memsz may exceed filesz. A segment can ask for more memory than it
 * occupies in the file, with the loader zeroing the difference - which is what
 * .bss is. A program wanting a megabyte of zeroed space needs no file to hold
 * the zeroes.
 *
 * VALIDATION
 *
 * Every field here came off a disk and is therefore untrusted, exactly like a
 * syscall argument. A malformed header could ask us to copy from beyond the end
 * of the file, or to map a page over kernel memory. Both are checked below.
 * Loaders that skip these checks are a well-trodden source of privilege
 * escalation.
 */

#include "loader.h"
#include "fs.h"
#include "pmm.h"
#include "paging.h"
#include "kheap.h"
#include "string.h"
#include "terminal.h"
#include "syscall.h"
#include "tss.h"
#include "task.h"

/* Generated by build.sh from user/prog.bin. */
#include "elf.h"

/* Generated by build.sh from user/prog.c. */
#include "prog_blob.h"

extern void usermode_jump(uint32_t entry, uint32_t user_stack_top);

#define MAX_PROGRAM (64 * 1024)

static uint32_t stack_base = 0;

int loader_install(const char *name)
{
	return fs_create(name, prog_blob, prog_blob_length);
}

/* Convert ELF segment permissions into page table flags.
 *
 * Note these are different bit values for the same ideas, so this translation
 * is mandatory rather than cosmetic. Note also what is missing: PF_X has no
 * counterpart, because 32-bit paging has no no-execute bit. Every mapped page
 * is executable whether the program asked for it or not. Long mode is where
 * that gets fixed.
 */
static uint32_t flags_for_segment(uint32_t elf_flags)
{
	uint32_t flags = PAGE_PRESENT | PAGE_USER;

	if (elf_flags & PF_W)
		flags |= PAGE_WRITE;

	return flags;
}

/* Record of what we mapped, so it can all be undone afterwards. */
#define MAX_SEGMENTS 8

static struct {
	uint32_t vaddr;
	uint32_t phys;
	uint32_t pages;
} loaded[MAX_SEGMENTS];

static uint32_t loaded_count = 0;

static int load_segment(const uint8_t *file, uint32_t file_size,
                        const struct elf_program_header *ph)
{
	/* The segment may start partway into a page. Round the address down and
	 * account for the offset, or the copy lands in the wrong place. */
	uint32_t page_start = ph->vaddr & ~(PAGE_SIZE - 1);
	uint32_t within     = ph->vaddr - page_start;
	uint32_t pages      = (within + ph->memsz + PAGE_SIZE - 1) / PAGE_SIZE;

	if (pages == 0 || loaded_count >= MAX_SEGMENTS)
		return 0;

	/* Untrusted input. A header claiming a huge filesz, or an offset past the
	 * end, would otherwise have us read whatever follows the buffer. */
	if (ph->filesz > ph->memsz)
		return 0;
	if (ph->offset > file_size || ph->filesz > file_size - ph->offset)
		return 0;

	/* And refuse to map anywhere outside the region set aside for programs.
	 * Without this, a crafted ELF could ask to be mapped over kernel memory
	 * and the loader would oblige. */
	if (ph->vaddr < USER_LOAD_ADDR || ph->vaddr + ph->memsz > USER_STACK_TOP)
		return 0;

	uint32_t phys = pmm_alloc_frames(pages);
	if (!phys)
		return 0;

	/* Zero first, then copy. That is what makes memsz larger than filesz work
	 * - the remainder is already zeroed - and it also guarantees no leftover
	 * data from a previous owner of these frames reaches the program. */
	kmemset((void *) phys, 0, pages * PAGE_SIZE);
	kmemcpy((void *)(phys + within), file + ph->offset, ph->filesz);

	uint32_t flags = flags_for_segment(ph->flags);

	for (uint32_t i = 0; i < pages; i++) {
		if (!paging_map(page_start + i * PAGE_SIZE,
		                phys + i * PAGE_SIZE, flags)) {
			for (uint32_t j = 0; j < pages; j++)
				pmm_free_frame(phys + j * PAGE_SIZE);
			return 0;
		}
	}

	loaded[loaded_count].vaddr = page_start;
	loaded[loaded_count].phys  = phys;
	loaded[loaded_count].pages = pages;
	loaded_count++;

	kprintf("  segment at 0x%x  %u bytes in file, %u in memory  %s%s\n",
	        ph->vaddr, ph->filesz, ph->memsz,
	        (ph->flags & PF_R) ? "r" : "-",
	        (ph->flags & PF_W) ? "w" : "-");

	return 1;
}

static void unload(void)
{
	for (uint32_t i = 0; i < loaded_count; i++) {
		for (uint32_t p = 0; p < loaded[i].pages; p++)
			paging_unmap(loaded[i].vaddr + p * PAGE_SIZE);

		for (uint32_t p = 0; p < loaded[i].pages; p++)
			pmm_free_frame(loaded[i].phys + p * PAGE_SIZE);
	}
	loaded_count = 0;

	if (stack_base) {
		uint32_t pages = USER_STACK_SIZE / PAGE_SIZE;
		uint32_t stack_bottom = USER_STACK_TOP - USER_STACK_SIZE;

		for (uint32_t i = 0; i < pages; i++)
			paging_unmap(stack_bottom + i * PAGE_SIZE);

		for (uint32_t i = 0; i < pages; i++)
			pmm_free_frame(stack_base + i * PAGE_SIZE);

		stack_base = 0;
	}
}

int loader_run(const char *name)
{
	uint32_t size = 0;

	uint8_t *file = (uint8_t *) kmalloc(MAX_PROGRAM);
	if (!file) {
		kprintf("loader: out of heap\n");
		return 0;
	}

	if (!fs_read(name, file, MAX_PROGRAM, &size) || size < sizeof(struct elf_header)) {
		kprintf("loader: cannot read %s\n", name);
		kfree(file);
		return 0;
	}

	const struct elf_header *elf = (const struct elf_header *) file;

	if (elf->ident[0] != ELF_MAGIC0 || elf->ident[1] != ELF_MAGIC1 ||
	    elf->ident[2] != ELF_MAGIC2 || elf->ident[3] != ELF_MAGIC3) {
		kprintf("loader: %s is not an ELF file\n", name);
		kfree(file);
		return 0;
	}

	if (elf->ident[4] != ELFCLASS32 || elf->ident[5] != ELFDATA2LSB ||
	    elf->type != ET_EXEC || elf->machine != EM_386) {
		kprintf("loader: %s is not a 32-bit x86 executable\n", name);
		kfree(file);
		return 0;
	}

	if (elf->phoff + (uint32_t) elf->phnum * elf->phentsize > size) {
		kprintf("loader: program header table runs past the end of the file\n");
		kfree(file);
		return 0;
	}

	kprintf("loader: %s, %u bytes, entry 0x%x, %u segments\n",
	        name, size, elf->entry, (uint32_t) elf->phnum);

	loaded_count = 0;

	for (uint32_t i = 0; i < elf->phnum; i++) {
		const struct elf_program_header *ph =
			(const struct elf_program_header *)
			(file + elf->phoff + i * elf->phentsize);

		if (ph->type != PT_LOAD)
			continue;                  /* not our business */

		if (!load_segment(file, size, ph)) {
			kprintf("loader: bad or unloadable segment %u\n", i);
			unload();
			kfree(file);
			return 0;
		}
	}

	kfree(file);

	if (loaded_count == 0) {
		kprintf("loader: nothing to load\n");
		return 0;
	}

	uint32_t stack_pages = USER_STACK_SIZE / PAGE_SIZE;
	stack_base = pmm_alloc_frames(stack_pages);
	if (!stack_base) {
		kprintf("loader: no memory for the stack\n");
		unload();
		return 0;
	}
	kmemset((void *) stack_base, 0, USER_STACK_SIZE);

	uint32_t stack_bottom = USER_STACK_TOP - USER_STACK_SIZE;
	for (uint32_t i = 0; i < stack_pages; i++) {
		if (!paging_map(stack_bottom + i * PAGE_SIZE,
		                stack_base + i * PAGE_SIZE,
		                PAGE_PRESENT | PAGE_USER | PAGE_WRITE)) {
			kprintf("loader: could not map the stack\n");
			unload();
			return 0;
		}
	}

	syscall_set_user_range(USER_LOAD_ADDR, USER_STACK_TOP);

	uint32_t kernel_stack;
	__asm__ volatile ("mov %%esp, %0" : "=r" (kernel_stack));
	tss_set_kernel_stack(kernel_stack - 256);

	/* The entry point comes from the file, not from an assumption. */
	usermode_jump(elf->entry, USER_STACK_TOP - 16);

	unload();
	return 1;
}
