/* loader.c - turning a file into a running program.
 *
 * This is where everything so far comes together. Read bytes from ArthicFS,
 * ask the frame allocator for physical memory, use the MMU to make that memory
 * appear at the address the program was linked for, mark it user-accessible,
 * and drop to ring 3. Filesystem, allocator, paging, TSS, syscalls - all of it,
 * for one purpose.
 *
 * WHY A FLAT BINARY IS NOT ENOUGH
 *
 * The program is a raw image: no header, no metadata, entry point assumed to be
 * the first byte. That works, and it is exactly why real systems do not do it.
 *
 * A flat binary cannot tell you where its code ends and its data begins, so the
 * loader has no way to map code read-only and data writable - the whole image
 * has to get one set of permissions. It cannot say how much zeroed space it
 * wants for uninitialised variables, so .bss has to be part of the file rather
 * than described by it. It cannot say which address it was linked for, so that
 * knowledge lives in the loader instead, and a program linked for anywhere else
 * silently misbehaves.
 *
 * ELF exists to answer those questions. Its program headers say "map this range
 * here, read and execute" and "this range there, read and write, and zero the
 * last N bytes". Parsing it is not hard, and it is the natural next step.
 *
 * For now we map the whole image READ-ONLY, which is the conservative choice: a
 * program that tries to write to its own data will fault rather than get away
 * with it. Since 32-bit paging has no NX bit, the image is executable whether
 * we like it or not, so making it non-writable is the only half of W^X
 * available.
 */

#include "loader.h"
#include "fs.h"
#include "pmm.h"
#include "paging.h"
#include "kheap.h"
#include "string.h"
#include "terminal.h"
#include "syscall.h"
#include "tss.h"
#include "task.h"

/* Generated by build.sh from user/prog.bin. */
#include "prog_blob.h"

extern void usermode_jump(uint32_t entry, uint32_t user_stack_top);

#define MAX_PROGRAM (64 * 1024)

static uint32_t image_frames = 0;
static uint32_t image_base   = 0;
static uint32_t stack_base   = 0;

int loader_install(const char *name)
{
	return fs_create(name, prog_blob, prog_blob_length);
}

static void unload(void)
{
	if (image_base) {
		for (uint32_t i = 0; i < image_frames; i++)
			paging_unmap(USER_LOAD_ADDR + i * PAGE_SIZE);

		for (uint32_t i = 0; i < image_frames; i++)
			pmm_free_frame(image_base + i * PAGE_SIZE);

		image_base = 0;
	}

	if (stack_base) {
		uint32_t pages = USER_STACK_SIZE / PAGE_SIZE;
		uint32_t stack_bottom = USER_STACK_TOP - USER_STACK_SIZE;

		for (uint32_t i = 0; i < pages; i++)
			paging_unmap(stack_bottom + i * PAGE_SIZE);

		for (uint32_t i = 0; i < pages; i++)
			pmm_free_frame(stack_base + i * PAGE_SIZE);

		stack_base = 0;
	}
}

int loader_run(const char *name)
{
	uint32_t size = 0;

	uint8_t *scratch = (uint8_t *) kmalloc(MAX_PROGRAM);
	if (!scratch) {
		kprintf("loader: out of heap\n");
		return 0;
	}

	if (!fs_read(name, scratch, MAX_PROGRAM, &size) || size == 0) {
		kprintf("loader: cannot read %s\n", name);
		kfree(scratch);
		return 0;
	}

	uint32_t pages = (size + PAGE_SIZE - 1) / PAGE_SIZE;

	image_base = pmm_alloc_frames(pages);
	if (!image_base) {
		kprintf("loader: no memory for the image\n");
		kfree(scratch);
		return 0;
	}

	/* Copy through the identity mapping - the frames are reachable at their
	 * own physical addresses right now, and will shortly also be reachable at
	 * USER_LOAD_ADDR. The same memory, under two names. */
	kmemcpy((void *) image_base, scratch, size);

	/* Zero the tail of the last page. Whatever the allocator handed us may
	 * hold another program's data, and letting a new program read it would be
	 * an information leak across a privilege boundary. */
	uint32_t tail = pages * PAGE_SIZE - size;
	if (tail)
		kmemset((void *)(image_base + size), 0, tail);

	kfree(scratch);

	uint32_t stack_pages = USER_STACK_SIZE / PAGE_SIZE;
	stack_base = pmm_alloc_frames(stack_pages);
	if (!stack_base) {
		kprintf("loader: no memory for the stack\n");
		unload();
		return 0;
	}
	kmemset((void *) stack_base, 0, USER_STACK_SIZE);

	image_frames = pages;

	/* The image: present, user-accessible, NOT writable. */
	for (uint32_t i = 0; i < pages; i++) {
		if (!paging_map(USER_LOAD_ADDR + i * PAGE_SIZE,
		                image_base + i * PAGE_SIZE,
		                PAGE_PRESENT | PAGE_USER)) {
			kprintf("loader: could not map the image\n");
			unload();
			return 0;
		}
	}

	/* The stack: writable, and it would be non-executable if this
	 * architecture had a bit for that. */
	uint32_t stack_bottom = USER_STACK_TOP - USER_STACK_SIZE;
	for (uint32_t i = 0; i < stack_pages; i++) {
		if (!paging_map(stack_bottom + i * PAGE_SIZE,
		                stack_base + i * PAGE_SIZE,
		                PAGE_PRESENT | PAGE_USER | PAGE_WRITE)) {
			kprintf("loader: could not map the stack\n");
			unload();
			return 0;
		}
	}

	/* The only addresses this program may hand back to the kernel. Anything
	 * else gets rejected by the syscall layer. */
	syscall_set_user_range(USER_LOAD_ADDR, USER_STACK_TOP);

	uint32_t kernel_stack;
	__asm__ volatile ("mov %%esp, %0" : "=r" (kernel_stack));
	tss_set_kernel_stack(kernel_stack - 256);

	kprintf("loader: %s, %u bytes, %u pages at 0x%x\n",
	        name, size, pages, USER_LOAD_ADDR);

	usermode_jump(USER_LOAD_ADDR, USER_STACK_TOP - 16);

	/* Back from ring 3. Tear the mapping down so the addresses mean nothing
	 * again, and give the frames back. */
	unload();

	return 1;
}
