/* loader.c - turning a file into a running program.
 *
 * This is where everything so far comes together. Read bytes from ArthicFS,
 * ask the frame allocator for physical memory, use the MMU to make that memory
 * appear at the address the program was linked for, mark it user-accessible,
 * and drop to ring 3. Filesystem, allocator, paging, TSS, syscalls - all of it,
 * for one purpose.
 *
 * THE PROGRAM DESCRIBES ITSELF
 *
 * The file is ELF. Rather than the loader knowing where the program wants to
 * live and guessing at its structure, the program says so: an entry point, and
 * a table of segments each carrying an address, a size, and permissions.
 *
 * The loader's job becomes mechanical - walk the program headers, and for each
 * one that says PT_LOAD, put the requested bytes at the requested address with
 * the requested flags. No assumptions.
 *
 * WHAT THAT BUYS
 *
 * Code is mapped read-only and executable; writable data is mapped read-write.
 * The program cannot modify its own instructions, which with a flat image was
 * impossible to arrange because nothing distinguished the two.
 *
 * And memsz may exceed filesz. A segment can ask for more memory than it
 * occupies in the file, with the loader zeroing the difference - which is what
 * .bss is. A program wanting a megabyte of zeroed space needs no file to hold
 * the zeroes.
 *
 * VALIDATION
 *
 * Every field here came off a disk and is therefore untrusted, exactly like a
 * syscall argument. A malformed header could ask us to copy from beyond the end
 * of the file, or to map a page over kernel memory. Both are checked below.
 * Loaders that skip these checks are a well-trodden source of privilege
 * escalation.
 */

#include "loader.h"
#include "fs.h"
#include "pmm.h"
#include "paging.h"
#include "kheap.h"
#include "string.h"
#include "terminal.h"
#include "syscall.h"
#include "tss.h"
#include "task.h"
#include "util.h"

/* Generated by build.sh from user/prog.bin. */
#include "elf.h"

/* Generated by build.sh from user/prog.c. */
#include "prog_blob.h"

extern void usermode_jump(uint32_t entry, uint32_t user_stack_top);

#define MAX_PROGRAM (64 * 1024)


int loader_install(const char *name)
{
	return fs_create(name, prog_blob, prog_blob_length);
}

/* Convert ELF segment permissions into page table flags.
 *
 * Note these are different bit values for the same ideas, so this translation
 * is mandatory rather than cosmetic. Note also what is missing: PF_X has no
 * counterpart, because 32-bit paging has no no-execute bit. Every mapped page
 * is executable whether the program asked for it or not. Long mode is where
 * that gets fixed.
 */
static uint32_t flags_for_segment(uint32_t elf_flags)
{
	uint32_t flags = PAGE_PRESENT | PAGE_USER;

	if (elf_flags & PF_W)
		flags |= PAGE_WRITE;

	return flags;
}

/* Record of what one running program owns, so it can all be undone when it
 * exits. One of these per program rather than a set of globals - two programs
 * are loaded at the same addresses and must not share bookkeeping. */
#define MAX_SEGMENTS 8

struct program {
	uint32_t page_dir;
	uint32_t entry;

	struct {
		uint32_t vaddr;
		uint32_t phys;
		uint32_t pages;
	} segment[MAX_SEGMENTS];

	uint32_t segments;
	uint32_t stack_phys;
	uint32_t args_phys;
	char     name[32];
	int      in_use;
};

#define MAX_PROGRAMS 4
static struct program programs[MAX_PROGRAMS];

static int load_segment(struct program *prog, const uint8_t *file,
                        uint32_t file_size, const struct elf_program_header *ph)
{
	/* The segment may start partway into a page. Round the address down and
	 * account for the offset, or the copy lands in the wrong place. */
	uint32_t page_start = KALIGN_DOWN(ph->vaddr, PAGE_SIZE);
	uint32_t within     = ph->vaddr - page_start;
	uint32_t pages      = KDIV_ROUND_UP(within + ph->memsz, PAGE_SIZE);

	if (pages == 0 || prog->segments >= MAX_SEGMENTS)
		return 0;

	/* Untrusted input. A header claiming a huge filesz, or an offset past the
	 * end, would otherwise have us read whatever follows the buffer. */
	if (ph->filesz > ph->memsz)
		return 0;
	if (ph->offset > file_size || ph->filesz > file_size - ph->offset)
		return 0;

	/* And refuse to map anywhere outside the region set aside for programs.
	 * Without this, a crafted ELF could ask to be mapped over kernel memory
	 * and the loader would oblige. */
	if (ph->vaddr < USER_LOAD_ADDR || ph->vaddr + ph->memsz > USER_STACK_TOP)
		return 0;

	uint32_t phys = pmm_alloc_frames(pages);
	if (!phys)
		return 0;

	/* Zero first, then copy. That is what makes memsz larger than filesz work
	 * - the remainder is already zeroed - and it also guarantees no leftover
	 * data from a previous owner of these frames reaches the program. */
	kmemset((void *) phys, 0, pages * PAGE_SIZE);
	kmemcpy((void *)(phys + within), file + ph->offset, ph->filesz);

	uint32_t flags = flags_for_segment(ph->flags);

	if (!paging_map_range(page_start, phys, pages, flags)) {
		pmm_free_range(phys, pages);
		return 0;
	}

	prog->segment[prog->segments].vaddr = page_start;
	prog->segment[prog->segments].phys  = phys;
	prog->segment[prog->segments].pages = pages;
	prog->segments++;

	kprintf("  segment at 0x%x  %u bytes in file, %u in memory  %s%s\n",
	        ph->vaddr, ph->filesz, ph->memsz,
	        (ph->flags & PF_R) ? "r" : "-",
	        (ph->flags & PF_W) ? "w" : "-");

	return 1;
}

static void unload(struct program *prog)
{
	for (uint32_t i = 0; i < prog->segments; i++)
		pmm_free_range(prog->segment[i].phys, prog->segment[i].pages);

	prog->segments = 0;

	if (prog->args_phys) {
		pmm_free_frame(prog->args_phys);
		prog->args_phys = 0;
	}

	if (prog->stack_phys) {
		pmm_free_range(prog->stack_phys, USER_STACK_SIZE / PAGE_SIZE);
		prog->stack_phys = 0;
	}

	/* Destroying the address space frees the page tables it added. There is
	 * no need to unmap anything first - the mappings only ever existed inside
	 * this directory, and it is about to stop existing. That is the quiet
	 * advantage of per-process address spaces: teardown is one operation
	 * rather than a careful walk. */
	if (prog->page_dir) {
		paging_destroy_address_space(prog->page_dir);
		prog->page_dir = 0;
	}

	prog->in_use = 0;
}

/* The body of a program task: build the address space, load the file into it,
 * drop to ring 3, and clean up on the way out. */
/* Called by the reaper once this program's task is off the run queue. */
static void program_cleanup(void *arg)
{
	struct program *prog = (struct program *) arg;
	if (prog)
		unload(prog);
}

static void program_task(void)
{
	struct task *self = task_current();
	struct program *prog = self ? (struct program *) self->arg : 0;

	if (!prog) {
		kprintf("loader: task started with no program attached\n");
		return;
	}

	/* The scheduler keeps the TSS pointed at this task's kernel stack, so
	 * there is nothing to set here. */
	syscall_set_user_range(USER_LOAD_ADDR, USER_STACK_TOP);

	/* Does not return. The program leaves ring 3 by exiting or by faulting,
	 * and either way the kernel kills the task rather than unwinding back
	 * through this function - see task_terminate. Cleanup happens in
	 * program_cleanup once the task is off the run queue. */
	usermode_jump(prog->entry, USER_STACK_TOP - 16);
}

int loader_run(const char *name, const char *args)
{
	struct program *prog = 0;

	for (uint32_t i = 0; i < MAX_PROGRAMS; i++) {
		if (!programs[i].in_use) {
			prog = &programs[i];
			break;
		}
	}

	if (!prog) {
		kprintf("loader: too many programs running\n");
		return 0;
	}

	kmemset(prog, 0, sizeof(*prog));

	uint32_t size = 0;
	uint8_t *file = (uint8_t *) kmalloc(MAX_PROGRAM);
	if (!file) {
		kprintf("loader: out of heap\n");
		return 0;
	}

	if (!fs_read(name, file, MAX_PROGRAM, &size) ||
	    size < sizeof(struct elf_header)) {
		kprintf("loader: cannot read %s\n", name);
		kfree(file);
		return 0;
	}

	const struct elf_header *elf = (const struct elf_header *) file;

	if (elf->ident[0] != ELF_MAGIC0 || elf->ident[1] != ELF_MAGIC1 ||
	    elf->ident[2] != ELF_MAGIC2 || elf->ident[3] != ELF_MAGIC3) {
		kprintf("loader: %s is not an ELF file\n", name);
		kfree(file);
		return 0;
	}

	if (elf->ident[4] != ELFCLASS32 || elf->ident[5] != ELFDATA2LSB ||
	    elf->type != ET_EXEC || elf->machine != EM_386) {
		kprintf("loader: %s is not a 32-bit x86 executable\n", name);
		kfree(file);
		return 0;
	}

	if (elf->phoff + (uint32_t) elf->phnum * elf->phentsize > size) {
		kprintf("loader: program header table runs past the end of the file\n");
		kfree(file);
		return 0;
	}

	/* A private address space, then switch to it so the mapping calls below
	 * apply there rather than to the kernel's. Safe because the kernel is
	 * mapped identically in both. */
	prog->page_dir = paging_create_address_space();
	if (!prog->page_dir) {
		kprintf("loader: no memory for an address space\n");
		kfree(file);
		return 0;
	}

	uint32_t saved = paging_kernel_directory();
	paging_switch(prog->page_dir);

	for (uint32_t i = 0; i < elf->phnum; i++) {
		const struct elf_program_header *ph =
			(const struct elf_program_header *)
			(file + elf->phoff + i * elf->phentsize);

		if (ph->type != PT_LOAD)
			continue;

		if (!load_segment(prog, file, size, ph)) {
			kprintf("loader: bad or unloadable segment %u\n", i);
			paging_switch(saved);
			unload(prog);
			kfree(file);
			return 0;
		}
	}

	kfree(file);

	if (prog->segments == 0) {
		kprintf("loader: nothing to load\n");
		paging_switch(saved);
		unload(prog);
		return 0;
	}

	uint32_t stack_pages = USER_STACK_SIZE / PAGE_SIZE;
	prog->stack_phys = pmm_alloc_frames(stack_pages);
	if (!prog->stack_phys) {
		kprintf("loader: no memory for the stack\n");
		paging_switch(saved);
		unload(prog);
		return 0;
	}
	kmemset((void *) prog->stack_phys, 0, USER_STACK_SIZE);

	uint32_t stack_bottom = USER_STACK_TOP - USER_STACK_SIZE;
	if (!paging_map_range(stack_bottom, prog->stack_phys, stack_pages,
	                      PAGE_PRESENT | PAGE_USER | PAGE_WRITE)) {
		kprintf("loader: could not map the stack\n");
		paging_switch(saved);
		unload(prog);
		return 0;
	}

	/* The argument page. Read-only from ring 3 - a program has no business
	 * rewriting what it was told. */
	prog->args_phys = pmm_alloc_frame();
	if (prog->args_phys) {
		char *dest = (char *) prog->args_phys;
		kmemset(dest, 0, PAGE_SIZE);

		kstrlcpy(dest, args ? args : "", USER_ARGS_MAX);

		paging_map(USER_ARGS_ADDR, prog->args_phys,
		           PAGE_PRESENT | PAGE_USER);
	}

	paging_switch(saved);

	prog->entry  = elf->entry;
	prog->in_use = 1;

	kprintf("loader: %s, %u bytes, entry 0x%x, %u segments, own address space\n",
	        name, size, elf->entry, prog->segments);

	/* The program becomes a task. The shell keeps running, and two programs
	 * can be resident at once - both mapped at 0x20000000, in different
	 * physical memory, neither able to see the other. */
	/* Everything the task needs is passed in, because it may be scheduled
	 * before this function returns. */
	if (!task_create_ex("prog", program_task, prog->page_dir, prog,
	                    program_cleanup)) {
		kprintf("loader: could not create a task for it\n");
		unload(prog);
		return 0;
	}

	return 1;
}
